import {mkdirSync, writeFileSync} from 'node:fs';
import {dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {clampRgb, converter, formatHex, parse} from 'culori';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = resolve(root, 'themes');
const toOklch = converter('oklch');
const toRgb = converter('rgb');

const presets = [
  ['graphite', '#1b1c1a'],
  ['fjord', '#172333'],
  ['paper', '#f1ece4'],
];

const args = process.argv.slice(2);
const themes = args.length >= 2 ? [[args[0], args[1]]] : presets;

mkdirSync(outDir, {recursive: true});

for (const [id, seed] of themes) {
  writeFileSync(resolve(outDir, `${id}.css`), themeCss(id, seed), 'utf8');
  console.log(`theme ${id}: ${seed}`);
}

function themeCss(id, seedHex) {
  const seed = parse(seedHex);
  if (!seed) throw new Error(`Invalid seed color: ${seedHex}`);
  const base = toOklch(seed);
  const dark = base.l < 0.56;
  const hue = Number.isFinite(base.h) ? base.h : 260;
  const chroma = Math.min(Math.max(base.c || 0.012, 0.012), dark ? 0.035 : 0.026);
  const accentHue = companionHue(hue, base.c || 0);
  const vars = dark ? darkTheme(hue, chroma, accentHue) : lightTheme(hue, chroma, accentHue);
  return `/* Generated by scripts/generate-theme.mjs from ${seedHex}. */\n:root[data-theme="${id}"] {\n${Object.entries(vars)
    .map(([name, value]) => `  ${name}: ${value};`)
    .join('\n')}\n}\n`;
}

function darkTheme(hue, chroma, accentHue) {
  const bg = tone(0.22, chroma, hue);
  return {
    'color-scheme': 'dark',
    '--bg': bg,
    '--panel': tone(0.30, chroma, hue),
    '--composer': tone(0.36, chroma, hue),
    '--trace-panel': tone(0.25, chroma, hue),
    '--artifact-panel': tone(0.27, chroma, hue),
    '--warning-bg': tone(0.31, 0.045, 84),
    '--warning-line': tone(0.62, 0.12, 88),
    '--warning-text': tone(0.84, 0.11, 92),
    '--line': tone(0.43, Math.min(chroma + 0.006, 0.038), hue),
    '--text': tone(0.90, 0.012, hue),
    '--muted': tone(0.69, 0.010, hue),
    '--accent': tone(0.76, 0.11, accentHue),
    '--accent-strong': tone(0.84, 0.13, accentHue),
    '--user': tone(0.29, chroma, hue),
    '--assistant': tone(0.24, chroma, hue),
    '--success': tone(0.67, 0.14, 150),
    '--danger': tone(0.67, 0.16, 28),
    '--error': tone(0.67, 0.16, 28),
    '--control-bg': tone(0.90, 0.010, hue),
    '--control-hover': tone(0.96, 0.008, hue),
    '--control-fg': bg,
    '--badge-bg': tone(0.62, 0.15, 245),
    '--badge-text': tone(0.98, 0.006, hue),
    '--trace-neutral': tone(0.68, 0.012, hue),
  };
}

function lightTheme(hue, chroma, accentHue) {
  const bg = tone(0.96, Math.min(chroma, 0.018), hue);
  return {
    'color-scheme': 'light',
    '--bg': bg,
    '--panel': tone(0.995, 0.006, hue),
    '--composer': tone(0.99, 0.007, hue),
    '--trace-panel': tone(0.985, 0.007, hue),
    '--artifact-panel': tone(0.98, 0.008, hue),
    '--warning-bg': tone(0.96, 0.045, 92),
    '--warning-line': tone(0.75, 0.10, 88),
    '--warning-text': tone(0.35, 0.09, 82),
    '--line': tone(0.84, 0.014, hue),
    '--text': tone(0.25, 0.020, hue),
    '--muted': tone(0.52, 0.014, hue),
    '--accent': tone(0.43, 0.12, accentHue),
    '--accent-strong': tone(0.34, 0.13, accentHue),
    '--user': tone(0.93, 0.022, accentHue),
    '--assistant': tone(0.995, 0.006, hue),
    '--success': tone(0.55, 0.13, 150),
    '--danger': tone(0.55, 0.15, 28),
    '--error': tone(0.55, 0.15, 28),
    '--control-bg': tone(0.28, 0.016, hue),
    '--control-hover': tone(0.20, 0.018, hue),
    '--control-fg': bg,
    '--badge-bg': tone(0.58, 0.15, 245),
    '--badge-text': tone(0.99, 0.006, hue),
    '--trace-neutral': tone(0.62, 0.012, hue),
  };
}

function companionHue(hue, chroma) {
  const turn = chroma < 0.035 ? 82 : 64;
  return (hue + turn) % 360;
}

function tone(l, c, h) {
  return formatHex(clampRgb(toRgb({mode: 'oklch', l, c, h})));
}
